-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 16:44:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `idPessoas` INT NOT NULL,
  `Telefone 1` VARCHAR(45) NOT NULL,
  `Telefone 2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `idPessoas_idx` (`idPessoas` ASC) VISIBLE,
  CONSTRAINT `idPessoas`
    FOREIGN KEY (`idPessoas`)
    REFERENCES `mydb`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoas` (
  `idPessoas` INT NOT NULL,
  `idHospedes` INT NOT NULL,
  `idTelefone` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoas`),
  INDEX `idHospedes_idx` (`idHospedes` ASC) VISIBLE,
  INDEX `idTelefone_idx` (`idTelefone` ASC) VISIBLE,
  CONSTRAINT `idHospedes`
    FOREIGN KEY (`idHospedes`)
    REFERENCES `mydb`.`Hospedes` (`idHospedes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTelefone`
    FOREIGN KEY (`idTelefone`)
    REFERENCES `mydb`.`Telefone` (`idTelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospedes` (
  `idHospedes` INT NOT NULL,
  `idPessoas` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHospedes`),
  INDEX `idPessoas_idx` (`idPessoas` ASC) VISIBLE,
  CONSTRAINT `idPessoas`
    FOREIGN KEY (`idPessoas`)
    REFERENCES `mydb`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos` (
  `idQuartos` INT NOT NULL,
  `Numero` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Preço_Diarial` INT NOT NULL,
  PRIMARY KEY (`idQuartos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservas` (
  `idReservas` INT NOT NULL,
  `idHospedes` INT NOT NULL,
  `Data_Checkin` DATE NOT NULL,
  `Data_Checkout` DATE NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `idHospedes_idx` (`idHospedes` ASC) VISIBLE,
  CONSTRAINT `idHospedes`
    FOREIGN KEY (`idHospedes`)
    REFERENCES `mydb`.`Hospedes` (`idHospedes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos_Reservados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos_Reservados` (
  `idQuartos_Reservados` INT NOT NULL,
  `idReservas` INT NOT NULL,
  `idQuartos` INT NOT NULL,
  PRIMARY KEY (`idQuartos_Reservados`),
  INDEX `idReservas_idx` (`idReservas` ASC) VISIBLE,
  INDEX `idQuartos_idx` (`idQuartos` ASC) VISIBLE,
  CONSTRAINT `idReservas`
    FOREIGN KEY (`idReservas`)
    REFERENCES `mydb`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idQuartos`
    FOREIGN KEY (`idQuartos`)
    REFERENCES `mydb`.`Quartos` (`idQuartos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `idPagamentos` INT NOT NULL,
  `idReservas` INT NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Metodo_Pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamentos`),
  INDEX `idReservas_idx` (`idReservas` ASC) VISIBLE,
  CONSTRAINT `idReservas`
    FOREIGN KEY (`idReservas`)
    REFERENCES `mydb`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
